<MyLayout>
    do_default_tab: False

    TabbedPanelItem:
        text: "ADMIN"
        Label:
            text: "This is the admin tab"

    TabbedPanelItem:
        text: "Accounts"
        BoxLayout:
            Label:
                text: "Press the button --->"
            Button:
                text:"Click Me"

    TabbedPanelItem:
        text: "Get Rich"
        Button:
            text: "This button does nothing"